name: "Publish container"

on:
  workflow_dispatch: # build on demand
  release:
    types: [published] # build on release

jobs:
  build:
    name: Build the container
    runs-on: ubuntu-latest
    permissions:
      contents: write # for uploading the SBOM to the release
      packages: write # for publishing the finished container to the registry
      security-events: write # for github/codeql-action/upload-sarif to upload the SARIF results
      id-token: write # to complete the identity challenge with sigstore/fulcio when running outside of PRs

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set version
        run: echo "VERSION=$(cat ${GITHUB_EVENT_PATH} | jq -r '.release.tag_name')" >> $GITHUB_ENV
        if: github.event_name == 'release'

      - name: Set short SHA
        run: echo "SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the container
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: false
          tags: ghcr.io/${{ github.repository }}/fizzbuzz:${{ env.SHA_SHORT }}

      - name: Scan it
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: "ghcr.io/${{ github.repository }}/fizzbuzz:${{ env.SHA_SHORT }}"
          fail-build: false

      - name: Upload the container scan report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Generate that SBOM
        uses: anchore/sbom-action@v0
        with:
          image: "ghcr.io/${{ github.repository }}/fizzbuzz:${{ env.SHA_SHORT }}"

      - name: Get image digest
        run: |
          echo "IMAGE_DIGEST=$(docker inspect \
          ghcr.io/${{ github.repository }}/fizzbuzz:${{ env.SHA_SHORT }} | \
          jq -r '.[0].Id')" >> $GITHUB_ENV

      - name: Install cosign
        uses: sigstore/cosign-installer@main

      - name: Log in to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Sign the published Docker image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign ghcr.io/${{ github.repository }}/fizzbuzz@${{ env.IMAGE_DIGEST }}

      - name: Push the signed image
        run: docker push ghcr.io/${{ github.repository }}/fizzbuzz:${{ env.SHA_SHORT }}
